name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build_pull_request:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        run: ./mvnw clean test